config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :medical_records
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  validates :level, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :medical_records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: %i[ show edit update destroy ]
  before_action :validate_required_input, only: %i[index]

  # GET /medical_records or /medical_records.json
  def index
    
      @min = 0
      @max = 0
      @avg = 0
      @user = User.find(params[:user_id])
      starDate = Date.parse(params[:from]).beginning_of_day
      endDate = Date.parse(params[:to]).end_of_day
      range = (starDate..endDate)


      @medical_records = MedicalRecord.where(
        user_id:params[:user_id],
        created_at: range
      ).order(:created_at)

      if !@medical_records.empty? 
        @max = @medical_records.pluck(:level).max
        @min= @medical_records.pluck(:level).min
        @avg = @medical_records.pluck(:level).inject{ |sum, el| sum + el } / @medical_records.size
      end
 
  end

  # GET /medical_records/new
  def new
    @medical_record = MedicalRecord.new
  end

  # POST /medical_records or /medical_records.json
  def create
    @medical_record = MedicalRecord.new(medical_record_params)


    respond_to do |format|
      if daily_limit_exceed 
        format.html { redirect_to user_url(@medical_record.user), notice: "Daily limit exceed"}
      elsif @medical_record.save 
        
        format.html { redirect_to user_url(@medical_record.user), notice: "Medical record was successfully created." }
        format.json { render :show, status: :created, location: @medical_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1 or /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to medical_record_url(@medical_record), notice: "Medical record was successfully updated." }
        format.json { render :show, status: :ok, location: @medical_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1 or /medical_records/1.json
  def destroy
    @medical_record.destroy

    respond_to do |format|
      format.html { redirect_to medical_records_url, notice: "Medical record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_record
      @medical_record = MedicalRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_record_params
      params.require(:medical_record).permit(:user_id, :level)
    end

    def report_params
      params.permit(:type, :timeframe)
    end

    def validate_required_input
      puts params[:to]
      puts params[:to].present?
      if params[:from].present? && params[:to].present? && params[:user_id].present?
        return true
      elsif !params[:to].present?
        flash[:notice] = "Report should have end date"
        redirect_back(fallback_location: root_path)
      else 
        redirect_to root_path, notice: "Report should be have user"
      end
    end

    def daily_limit_exceed
      return false if MedicalRecord.where(user_id:medical_record_params["user_id"]).count < 4
      
      MedicalRecord.where(user_id:medical_record_params["user_id"])
        .order(created_at: :desc)
        .take(4)
        .last
        .created_at
        .to_i > Date.today.beginning_of_day.to_i
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Blood Glucose Tracker", root_path, class:"navbar-brand"%>
   
    
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloodGlucoseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='container-fluid'>
    <%= render "layouts/navbar" %>
    <% if notice %>
      <div class="alert alert-info m-2" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/medical_records/index.html.erb
<h1><%= "#{@user.firstname.capitalize} #{@user.lastname.capitalize} Report"%></h1>

<div class="btn-toolbar mb-3 justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group me-2" role="group" aria-label="First group">
    <%= link_to "Daily", medical_records_path(:user_id => @user.id, :from => Date.today, :to=>Date.today), class:'btn btn-outline-primary' %>
    <%= link_to "Monthly", medical_records_path(:user_id => @user.id, :from => Date.today.last_month.beginning_of_month, :to=>Date.today.last_month.end_of_month), class:'btn btn-outline-primary' %>
  </div>
  <div class="input-group ">
    <%= form_with url: medical_records_path, method: :get do |f|%>
      <div class="input-group">
        <%= f.date_field :to, class:"form-control" %>
        <%= f.hidden_field :from, :value => Date.today.beginning_of_month, class:"form-control"  %>
        <%= f.hidden_field :user_id, :value => @user.id, class:"form-control"  %>
        <%= f.submit "Month To Date", class:"btn btn-outline-primary"%>
      </div>
    <% end %>
  </div>
</div>
  
</div>


<div id="medical_records">
  <div class='d-flex  justify-content-center'>
    <div class="mx-1"><strong>Mininmal</strong>: <%= @min%></div> |
    <div class="mx-1"><strong>Maximum</strong>: <%= @max%></div> |
    <div class="mx-1"><strong>Average</strong>: <%= @avg%></div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Level</th>
      </tr>
    </thead>
    <tbody>
      <% @medical_records.each do |medical_record| %>
        <tr>
          <td><%= medical_record.created_at.strftime('%F at %T') %></td>
          <td><%= medical_record.level %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

app/views/users/_form.html.erb
<div class='row m-2'>
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div class="alert alert-danger m-2" role="alert">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :firstname, class:"form-label" %>
      <%= form.text_field :firstname, class:"form-control"  %>
    </div>

    <div class="mb-3">
      <%= form.label :lastname, class:"form-label" %>
      <%= form.text_field :lastname, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= form.submit :class =>"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <h1> <%= @user.firstname.capitalize %> <%= @user.lastname.capitalize %></h1>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div class='row m-2'>
  <table class="table users">
    <thead class='thead-dark'>
      <tr>
        <th scope="col">#</th>
        <th scope="col">FirstName</th>
        <th scope="col">LastName</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class='my-2'>
          <th scope="row"><%= user.id %></th>
          <td><%= user.firstname %></td>
          <td><%= user.lastname %></td>
          <td> <%= link_to "Add Level", user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div type="button" class="btn btn-outline-primary">
    <%= link_to "New user", new_user_path, :class => "btn"%>
  </div>
</div>

app/views/users/new.html.erb
<div class='row m-4'>
  <h1>New user</h1>

  <%= render "form", user: @user %>

  <div>
    <%= link_to "Back to users", users_path, class:'btn btn-primary' %>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <div class='d-flex  mt-2 align-items-center'>
    <div class='mr-auto p-2'>
      <%= link_to @user do %>
        <%= @user.firstname.capitalize %> <%= @user.lastname.capitalize %>
      <% end %>
    </div>
    <div class="p-2">
      <%= link_to medical_records_path(:user_id => @user.id, :from => Date.today, :to=>Date.today), class:'btn btn-warning mx-1' do %> 
        <i class="bi bi-card-list"></i>
      <% end %>
    </div>
    <div class="p-2">
      <%= link_to edit_user_path(@user), class:'btn btn-primary mx-1' do %>
        <i class="bi bi-pen"></i>
      <% end %>
    </div>
    <div class="p-2">
      <%= button_to @user, method: :delete, class:'btn-danger btn mx-1' do%>
        <i class="bi bi-trash2"></i>
      <% end %>
    </div>
  </div> 
</div>
<div class='row m-1'>
  <%= form_with url: medical_records_path, 
      method: :post, 
      local: true , 
      scope: :medical_record do |f|%>
    <div class="input-group m-2">
      <%= f.text_field :level, type:'number', placeholder:"Enter your Blood glucose Level", class:"form-control"%>
      <%= f.hidden_field :user_id, :value => @user.id, class:"form-control"  %>
      <%= f.button "Add", type: "submit", class:"btn btn-outline-secondary", id:"button-addon2"%>
    </div>
  <% end %>
</div>